# Use a base Python image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application
COPY . /app

# Ensure the downloads directory exists
RUN mkdir -p /app/downloads

# Expose the port where your Flask server will run
EXPOSE 80

# Command to run the Flask application
CMD ["python", "dns_receiver.py"]
